layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  sort_by options:
     - pushed
     - stars
  limit: 15
  exclude:
    archived: true
    forks: false
    projects:
     - kisah-baru
     - repo-belajar 
     - bulanbahasa2017
     - w3schools-offline
     - webdesa-beku
     - desainkreatif

social_media:
  # behance: your_username
  dribbble: raniaamina
  # facebook: your_username
  # hackerrank: your_username
  instagram: raniaamina.id
  # keybase: your_username
  linkedin: raniaamina
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: raniaamina
  twitter: raniaamina_id
  # unsplash: your_username
  # vk: your_username
  # website: https://raniaamina.id
  # youtube: your_username

topics:
  - name: Tokusatsu
    web_url: https://tokusatsu.fandom.com/wiki/Tokusatsu
    image_url: /assets/img/tokusatsu.png
    
  - name: Gimpscape
    web_url: https://gimpscape.org
    image_url: /assets/img/gimpscape.png

  - name: Inkscape
    web_url: https://inkscpae.org
    image_url: /assets/img/inkscape.png
    
  - name: Gimp
    web_url: https://gimp.org
    image_url: /assets/img/gimp.png

  - name: Krita
    web_url: https://krita.org
    image_url: /assets/img/krita.png
    
  - name: Synfig
    web_url: https://synfig.org
    image_url: /assets/img/synfig.png
    
  - name: UI Design
    image_url: /assets/img/ui-design.png
    
  - name: Hexo
    web_url: https://hexo.io
    image_url: /assets/img/hexo.png
    
  - name: Bootstrap
    web_url: https://bootstrapstudio.io
    image_url: /assets/img/bss.png
